# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up
web:
  build: ./nginx-filebeat
  ports:
    - "80:80"
  links:
    - elk

elk:
  environment:
    - CLUSTER_NAME=olakk_es
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
