# Docker Compose file for ELK stack

version: '3'

services:

    #web:
    #  build: ./nginx-filebeat
    #  ports:
    #    - "80:80"
    #  links:
    #    - elk
    #
    elk:
      environment:
        - CLUSTER_NAME=thenga
        - LOGSTASH_START=0
      build: .
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"

    fluentd:
      build: ./fluentd
      environment:
        - FLUENTD_OPT=-v
      ports:
        - "24284:24284"
        - "24224:24224"
    # links:
    #    - elk
      depends_on:
        - elk
