version: 0.11-winbuild-{build}

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: if "%platform%"=="Win32" set msvc=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set msvc=Visual Studio 14 2015 Win64

build_script:
  - cd build
  - cmake -G "%msvc%" -DCMAKE_BUILD_TYPE=%configuration% -DFLB_WITHOUT_SHARED_LIB=On -DFLB_WITHOUT_EXAMPLES=On ..
  - cmake --build .
